#!/usr/bin/env bash
# install nginx web server on server
# the server hsould be listening on port 80
apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
