#!/usr/bin/env bash
# configure Nginx so that /redirect_me is redirecting to another page
apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
str_command="server_name _;\n\trewrite ^\/redirect_me https:\/\/https://www.youtube.com/watch?v=eCOdMdWbP_4 permanent;"
sed -i "s#server_name _;#$str_command#" /etc/nginx/sites-available/default
service nginx restart
