#!/usr/bin/env bash
# Configure Nginx to run on port 80

# check if nginx is installed
sudo apt-get update -y
sudo apt-get install nginx -y

# check if nginx is running
sudo service nginx start

# check if nginx is listening on port 80
sudo ufw allow 80

# restart nginx
sudo service nginx restart
