#!/usr/bin/env bash
# script that displays the PID, along with the process name, of processes whose name contain the word bash.
# without using ps
for pid in $(pgrep -f bash)
do
    echo "$pid $(cat /proc/"$pid"/comm)"
done
