#!/usr/bin/env bash
# bash scripts that prints numbers from 1 to 100
# but for multiples of three print Fizz instead of the number
# and for the multiples of five print Buzz
# for numbers which are multiples of both three and five print FizzBuzz
for i in {1..100}
do
    if [[ $((i%3)) == 0 && $((i%5)) == 0 ]]
    then
        echo "FizzBuzz"
    elif [[ $((i%3)) == 0 ]]
    then
        echo "Fizz"
    elif [[ $((i%5)) == 0 ]]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done
