#!/usr/bin/env bash
# bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
for i in {1..10}
do
    echo "Best School"
    if [[ $i == 9 ]]
    then
        echo "Hi"
    fi
done
