#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
# use while loop
for hour in {0..12}
do
    echo "Hour: $hour"
    for minutes in {1..59}
    do
        echo "$minutes"
    done
done
